# Generated by Django 6.0.3 on 2026-05-14 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
